using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "81a69f6bb0f95235")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Layout Declaration</summary>
	[PublishedContentModel("layoutDeclaration")]
	public partial class LayoutDeclaration : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "layoutDeclaration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LayoutDeclaration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LayoutDeclaration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// brand-name
		///</summary>
		[ImplementPropertyType("brandName")]
		public string BrandName
		{
			get { return this.GetPropertyValue<string>("brandName"); }
		}

		///<summary>
		/// copy-right
		///</summary>
		[ImplementPropertyType("copyRight")]
		public string CopyRight
		{
			get { return this.GetPropertyValue<string>("copyRight"); }
		}

		///<summary>
		/// list-navigators
		///</summary>
		[ImplementPropertyType("listNavigators")]
		public Umbraco.Web.Models.RelatedLinks ListNavigators
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listNavigators"); }
		}

		///<summary>
		/// list-others-ref
		///</summary>
		[ImplementPropertyType("listOthersRef")]
		public Umbraco.Web.Models.RelatedLinks ListOthersRef
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listOthersRef"); }
		}

		///<summary>
		/// list-products-ref
		///</summary>
		[ImplementPropertyType("listProductsRef")]
		public Umbraco.Web.Models.RelatedLinks ListProductsRef
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listProductsRef"); }
		}

		///<summary>
		/// mail-to
		///</summary>
		[ImplementPropertyType("mailTo")]
		public string MailTo
		{
			get { return this.GetPropertyValue<string>("mailTo"); }
		}

		///<summary>
		/// tab-icon
		///</summary>
		[ImplementPropertyType("tabIcon")]
		public IPublishedContent TabIcon
		{
			get { return this.GetPropertyValue<IPublishedContent>("tabIcon"); }
		}

		///<summary>
		/// tab-title
		///</summary>
		[ImplementPropertyType("tabTitle")]
		public string TabTitle
		{
			get { return this.GetPropertyValue<string>("tabTitle"); }
		}

		///<summary>
		/// telephone
		///</summary>
		[ImplementPropertyType("telephone")]
		public string Telephone
		{
			get { return this.GetPropertyValue<string>("telephone"); }
		}

		///<summary>
		/// title-list-others-ref
		///</summary>
		[ImplementPropertyType("titleListOthersRef")]
		public string TitleListOthersRef
		{
			get { return this.GetPropertyValue<string>("titleListOthersRef"); }
		}

		///<summary>
		/// title-list-products-ref
		///</summary>
		[ImplementPropertyType("titleListProductsRef")]
		public string TitleListProductsRef
		{
			get { return this.GetPropertyValue<string>("titleListProductsRef"); }
		}
	}

	/// <summary>Home Page Declaration</summary>
	[PublishedContentModel("homePageDeclaration")]
	public partial class HomePageDeclaration : LayoutDeclaration
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageDeclaration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageDeclaration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageDeclaration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// banner-1-description
		///</summary>
		[ImplementPropertyType("banner1Description")]
		public IHtmlString Banner1Description
		{
			get { return this.GetPropertyValue<IHtmlString>("banner1Description"); }
		}

		///<summary>
		/// banner-1-image
		///</summary>
		[ImplementPropertyType("banner1Image")]
		public IPublishedContent Banner1Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner1Image"); }
		}

		///<summary>
		/// banner-1-main-title
		///</summary>
		[ImplementPropertyType("banner1MainTitle")]
		public string Banner1MainTitle
		{
			get { return this.GetPropertyValue<string>("banner1MainTitle"); }
		}

		///<summary>
		/// banner-1-sub-title
		///</summary>
		[ImplementPropertyType("banner1SubTitle")]
		public string Banner1SubTitle
		{
			get { return this.GetPropertyValue<string>("banner1SubTitle"); }
		}

		///<summary>
		/// banner-2-description
		///</summary>
		[ImplementPropertyType("banner2Description")]
		public IHtmlString Banner2Description
		{
			get { return this.GetPropertyValue<IHtmlString>("banner2Description"); }
		}

		///<summary>
		/// banner-2-image
		///</summary>
		[ImplementPropertyType("banner2Image")]
		public IPublishedContent Banner2Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner2Image"); }
		}

		///<summary>
		/// banner-2-main-title
		///</summary>
		[ImplementPropertyType("banner2MainTitle")]
		public string Banner2MainTitle
		{
			get { return this.GetPropertyValue<string>("banner2MainTitle"); }
		}

		///<summary>
		/// banner-2-sub-title
		///</summary>
		[ImplementPropertyType("banner2SubTitle")]
		public string Banner2SubTitle
		{
			get { return this.GetPropertyValue<string>("banner2SubTitle"); }
		}

		///<summary>
		/// banner-3-description
		///</summary>
		[ImplementPropertyType("banner3Description")]
		public IHtmlString Banner3Description
		{
			get { return this.GetPropertyValue<IHtmlString>("banner3Description"); }
		}

		///<summary>
		/// banner-3-image
		///</summary>
		[ImplementPropertyType("banner3Image")]
		public IPublishedContent Banner3Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner3Image"); }
		}

		///<summary>
		/// banner-3-main-title
		///</summary>
		[ImplementPropertyType("banner3MainTitle")]
		public string Banner3MainTitle
		{
			get { return this.GetPropertyValue<string>("banner3MainTitle"); }
		}

		///<summary>
		/// banner-3-sub-title
		///</summary>
		[ImplementPropertyType("banner3SubTitle")]
		public string Banner3SubTitle
		{
			get { return this.GetPropertyValue<string>("banner3SubTitle"); }
		}

		///<summary>
		/// category-1-image
		///</summary>
		[ImplementPropertyType("category1Image")]
		public IPublishedContent Category1Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("category1Image"); }
		}

		///<summary>
		/// category-1-name
		///</summary>
		[ImplementPropertyType("category1Name")]
		public string Category1Name
		{
			get { return this.GetPropertyValue<string>("category1Name"); }
		}

		///<summary>
		/// category-2-image
		///</summary>
		[ImplementPropertyType("category2Image")]
		public IPublishedContent Category2Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("category2Image"); }
		}

		///<summary>
		/// category-2-name
		///</summary>
		[ImplementPropertyType("category2Name")]
		public string Category2Name
		{
			get { return this.GetPropertyValue<string>("category2Name"); }
		}

		///<summary>
		/// category-3-image
		///</summary>
		[ImplementPropertyType("category3Image")]
		public IPublishedContent Category3Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("category3Image"); }
		}

		///<summary>
		/// category-3-name
		///</summary>
		[ImplementPropertyType("category3Name")]
		public string Category3Name
		{
			get { return this.GetPropertyValue<string>("category3Name"); }
		}

		///<summary>
		/// description-category
		///</summary>
		[ImplementPropertyType("descriptionCategory")]
		public string DescriptionCategory
		{
			get { return this.GetPropertyValue<string>("descriptionCategory"); }
		}

		///<summary>
		/// description-feature
		///</summary>
		[ImplementPropertyType("descriptionFeature")]
		public string DescriptionFeature
		{
			get { return this.GetPropertyValue<string>("descriptionFeature"); }
		}

		///<summary>
		/// feature-1-description
		///</summary>
		[ImplementPropertyType("feature1Description")]
		public string Feature1Description
		{
			get { return this.GetPropertyValue<string>("feature1Description"); }
		}

		///<summary>
		/// feature-1-image
		///</summary>
		[ImplementPropertyType("feature1Image")]
		public IPublishedContent Feature1Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("feature1Image"); }
		}

		///<summary>
		/// feature-1-name
		///</summary>
		[ImplementPropertyType("feature1Name")]
		public string Feature1Name
		{
			get { return this.GetPropertyValue<string>("feature1Name"); }
		}

		///<summary>
		/// feature-1-price
		///</summary>
		[ImplementPropertyType("feature1Price")]
		public string Feature1Price
		{
			get { return this.GetPropertyValue<string>("feature1Price"); }
		}

		///<summary>
		/// feature-1-review
		///</summary>
		[ImplementPropertyType("feature1Review")]
		public string Feature1Review
		{
			get { return this.GetPropertyValue<string>("feature1Review"); }
		}

		///<summary>
		/// feature-2-description
		///</summary>
		[ImplementPropertyType("feature2Description")]
		public string Feature2Description
		{
			get { return this.GetPropertyValue<string>("feature2Description"); }
		}

		///<summary>
		/// feature-2-image
		///</summary>
		[ImplementPropertyType("feature2Image")]
		public IPublishedContent Feature2Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("feature2Image"); }
		}

		///<summary>
		/// feature-2-name
		///</summary>
		[ImplementPropertyType("feature2Name")]
		public string Feature2Name
		{
			get { return this.GetPropertyValue<string>("feature2Name"); }
		}

		///<summary>
		/// feature-2-price
		///</summary>
		[ImplementPropertyType("feature2Price")]
		public string Feature2Price
		{
			get { return this.GetPropertyValue<string>("feature2Price"); }
		}

		///<summary>
		/// feature-2-review
		///</summary>
		[ImplementPropertyType("feature2Review")]
		public string Feature2Review
		{
			get { return this.GetPropertyValue<string>("feature2Review"); }
		}

		///<summary>
		/// feature-3-description
		///</summary>
		[ImplementPropertyType("feature3Description")]
		public string Feature3Description
		{
			get { return this.GetPropertyValue<string>("feature3Description"); }
		}

		///<summary>
		/// feature-3-image
		///</summary>
		[ImplementPropertyType("feature3Image")]
		public IPublishedContent Feature3Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("feature3Image"); }
		}

		///<summary>
		/// feature-3-name
		///</summary>
		[ImplementPropertyType("feature3Name")]
		public string Feature3Name
		{
			get { return this.GetPropertyValue<string>("feature3Name"); }
		}

		///<summary>
		/// feature-3-price
		///</summary>
		[ImplementPropertyType("feature3Price")]
		public string Feature3Price
		{
			get { return this.GetPropertyValue<string>("feature3Price"); }
		}

		///<summary>
		/// feature-3-review
		///</summary>
		[ImplementPropertyType("feature3Review")]
		public string Feature3Review
		{
			get { return this.GetPropertyValue<string>("feature3Review"); }
		}

		///<summary>
		/// title-category
		///</summary>
		[ImplementPropertyType("titleCategory")]
		public string TitleCategory
		{
			get { return this.GetPropertyValue<string>("titleCategory"); }
		}

		///<summary>
		/// title-feature
		///</summary>
		[ImplementPropertyType("titleFeature")]
		public string TitleFeature
		{
			get { return this.GetPropertyValue<string>("titleFeature"); }
		}
	}

	/// <summary>ShopPage</summary>
	[PublishedContentModel("shopPage")]
	public partial class ShopPage : LayoutDeclaration
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "shopPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ShopPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ShopPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// categories
		///</summary>
		[ImplementPropertyType("categories")]
		public string Categories
		{
			get { return this.GetPropertyValue<string>("categories"); }
		}

		///<summary>
		/// list-category
		///</summary>
		[ImplementPropertyType("listCategory")]
		public Umbraco.Web.Models.RelatedLinks ListCategory
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listCategory"); }
		}

		///<summary>
		/// list-filter
		///</summary>
		[ImplementPropertyType("listFilter")]
		public Umbraco.Web.Models.RelatedLinks ListFilter
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listFilter"); }
		}

		///<summary>
		/// shoppage-brand-images
		///</summary>
		[ImplementPropertyType("shoppageBrandImages")]
		public IEnumerable<IPublishedContent> ShoppageBrandImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("shoppageBrandImages"); }
		}

		///<summary>
		/// shoppage-brand-section
		///</summary>
		[ImplementPropertyType("shoppageBrandSection")]
		public string ShoppageBrandSection
		{
			get { return this.GetPropertyValue<string>("shoppageBrandSection"); }
		}

		///<summary>
		/// shoppage-brand-section-description
		///</summary>
		[ImplementPropertyType("shoppageBrandSectionDescription")]
		public string ShoppageBrandSectionDescription
		{
			get { return this.GetPropertyValue<string>("shoppageBrandSectionDescription"); }
		}
	}

	/// <summary>AboutPage</summary>
	[PublishedContentModel("aboutPage")]
	public partial class AboutPage : LayoutDeclaration
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// aboutpage-brand-description
		///</summary>
		[ImplementPropertyType("aboutpageBrandDescription")]
		public string AboutpageBrandDescription
		{
			get { return this.GetPropertyValue<string>("aboutpageBrandDescription"); }
		}

		///<summary>
		/// aboutpage-brand-images
		///</summary>
		[ImplementPropertyType("aboutpageBrandImages")]
		public IEnumerable<IPublishedContent> AboutpageBrandImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("aboutpageBrandImages"); }
		}

		///<summary>
		/// aboutpage-brand-title
		///</summary>
		[ImplementPropertyType("aboutpageBrandTitle")]
		public string AboutpageBrandTitle
		{
			get { return this.GetPropertyValue<string>("aboutpageBrandTitle"); }
		}

		///<summary>
		/// aboutpage-description
		///</summary>
		[ImplementPropertyType("aboutpageDescription")]
		public string AboutpageDescription
		{
			get { return this.GetPropertyValue<string>("aboutpageDescription"); }
		}

		///<summary>
		/// aboutpage-hero-image
		///</summary>
		[ImplementPropertyType("aboutpageHeroImage")]
		public IPublishedContent AboutpageHeroImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("aboutpageHeroImage"); }
		}

		///<summary>
		/// aboutpage-service-description
		///</summary>
		[ImplementPropertyType("aboutpageServiceDescription")]
		public string AboutpageServiceDescription
		{
			get { return this.GetPropertyValue<string>("aboutpageServiceDescription"); }
		}

		///<summary>
		/// aboutpage-service-list
		///</summary>
		[ImplementPropertyType("aboutpageServiceList")]
		public IEnumerable<string> AboutpageServiceList
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("aboutpageServiceList"); }
		}

		///<summary>
		/// aboutpage-service-title
		///</summary>
		[ImplementPropertyType("aboutpageServiceTitle")]
		public string AboutpageServiceTitle
		{
			get { return this.GetPropertyValue<string>("aboutpageServiceTitle"); }
		}

		///<summary>
		/// aboutpage-title
		///</summary>
		[ImplementPropertyType("aboutpageTitle")]
		public string AboutpageTitle
		{
			get { return this.GetPropertyValue<string>("aboutpageTitle"); }
		}
	}

	/// <summary>LoginPage</summary>
	[PublishedContentModel("loginPage")]
	public partial class LoginPage : LayoutDeclaration
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "loginPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LoginPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LoginPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
