//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "d64b449f9df9ba88")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Layout Declaration</summary>
	[PublishedContentModel("layoutDeclaration")]
	public partial class LayoutDeclaration : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "layoutDeclaration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LayoutDeclaration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LayoutDeclaration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// brand-name
		///</summary>
		[ImplementPropertyType("brandName")]
		public string BrandName
		{
			get { return this.GetPropertyValue<string>("brandName"); }
		}

		///<summary>
		/// copy-right
		///</summary>
		[ImplementPropertyType("copyRight")]
		public string CopyRight
		{
			get { return this.GetPropertyValue<string>("copyRight"); }
		}

		///<summary>
		/// list navigators
		///</summary>
		[ImplementPropertyType("listNavigators")]
		public Umbraco.Web.Models.RelatedLinks ListNavigators
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listNavigators"); }
		}

		///<summary>
		/// list-others-ref
		///</summary>
		[ImplementPropertyType("listOthersRef")]
		public Umbraco.Web.Models.RelatedLinks ListOthersRef
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listOthersRef"); }
		}

		///<summary>
		/// list-products-ref
		///</summary>
		[ImplementPropertyType("listProductsRef")]
		public Umbraco.Web.Models.RelatedLinks ListProductsRef
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listProductsRef"); }
		}

		///<summary>
		/// mail-to
		///</summary>
		[ImplementPropertyType("mailTo")]
		public string MailTo
		{
			get { return this.GetPropertyValue<string>("mailTo"); }
		}

		///<summary>
		/// tab-icon
		///</summary>
		[ImplementPropertyType("tabIcon")]
		public IPublishedContent TabIcon
		{
			get { return this.GetPropertyValue<IPublishedContent>("tabIcon"); }
		}

		///<summary>
		/// tab-title
		///</summary>
		[ImplementPropertyType("tabTitle")]
		public string TabTitle
		{
			get { return this.GetPropertyValue<string>("tabTitle"); }
		}

		///<summary>
		/// telephone
		///</summary>
		[ImplementPropertyType("telephone")]
		public string Telephone
		{
			get { return this.GetPropertyValue<string>("telephone"); }
		}

		///<summary>
		/// title-list-others-ref
		///</summary>
		[ImplementPropertyType("titleListOthersRef")]
		public string TitleListOthersRef
		{
			get { return this.GetPropertyValue<string>("titleListOthersRef"); }
		}

		///<summary>
		/// title-list-products-ref
		///</summary>
		[ImplementPropertyType("titleListProductsRef")]
		public string TitleListProductsRef
		{
			get { return this.GetPropertyValue<string>("titleListProductsRef"); }
		}
	}

	/// <summary>Home Page Section 1</summary>
	[PublishedContentModel("homePageSection1")]
	public partial class HomePageSection1 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageSection1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageSection1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageSection1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// placeholder temp
		///</summary>
		[ImplementPropertyType("placeholderTemp")]
		public string PlaceholderTemp
		{
			get { return this.GetPropertyValue<string>("placeholderTemp"); }
		}
	}

	/// <summary>Home Page Section 2</summary>
	[PublishedContentModel("homePageSection2")]
	public partial class HomePageSection2 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageSection2";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageSection2(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageSection2, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// home section 2 description
		///</summary>
		[ImplementPropertyType("homeSection2Description")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection2Description
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection2Description"); }
		}

		///<summary>
		/// home section 2 title
		///</summary>
		[ImplementPropertyType("homeSection2Title")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection2Title
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection2Title"); }
		}
	}

	/// <summary>ShopPage Declaration</summary>
	[PublishedContentModel("shopPageDeclaration")]
	public partial class ShopPageDeclaration : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "shopPageDeclaration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ShopPageDeclaration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ShopPageDeclaration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// categories
		///</summary>
		[ImplementPropertyType("categories")]
		public string Categories
		{
			get { return this.GetPropertyValue<string>("categories"); }
		}

		///<summary>
		/// list category
		///</summary>
		[ImplementPropertyType("listCategory")]
		public Umbraco.Web.Models.RelatedLinks ListCategory
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listCategory"); }
		}

		///<summary>
		/// list filter
		///</summary>
		[ImplementPropertyType("listFilter")]
		public Umbraco.Web.Models.RelatedLinks ListFilter
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("listFilter"); }
		}

		///<summary>
		/// shoppage brand images
		///</summary>
		[ImplementPropertyType("shoppageBrandImages")]
		public IEnumerable<IPublishedContent> ShoppageBrandImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("shoppageBrandImages"); }
		}

		///<summary>
		/// shoppage brand section
		///</summary>
		[ImplementPropertyType("shoppageBrandSection")]
		public string ShoppageBrandSection
		{
			get { return this.GetPropertyValue<string>("shoppageBrandSection"); }
		}

		///<summary>
		/// shoppage brand section description
		///</summary>
		[ImplementPropertyType("shoppageBrandSectionDescription")]
		public string ShoppageBrandSectionDescription
		{
			get { return this.GetPropertyValue<string>("shoppageBrandSectionDescription"); }
		}
	}

	/// <summary>Home Page Declaration</summary>
	[PublishedContentModel("homePageDeclaration")]
	public partial class HomePageDeclaration : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageDeclaration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageDeclaration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageDeclaration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// placeholder temp
		///</summary>
		[ImplementPropertyType("placeholderTemp")]
		public string PlaceholderTemp
		{
			get { return this.GetPropertyValue<string>("placeholderTemp"); }
		}
	}

	/// <summary>Home Page Section 3</summary>
	[PublishedContentModel("homePageSection3")]
	public partial class HomePageSection3 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageSection3";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageSection3(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageSection3, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// home section 3 description
		///</summary>
		[ImplementPropertyType("homeSection3Description")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection3Description
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection3Description"); }
		}

		///<summary>
		/// home section 3 title
		///</summary>
		[ImplementPropertyType("homeSection3Title")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection3Title
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection3Title"); }
		}
	}

	/// <summary>About Page Declaration</summary>
	[PublishedContentModel("aboutPageDeclaration")]
	public partial class AboutPageDeclaration : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutPageDeclaration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutPageDeclaration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutPageDeclaration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// aboutpage brand description
		///</summary>
		[ImplementPropertyType("aboutpageBrandDescription")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> AboutpageBrandDescription
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("aboutpageBrandDescription"); }
		}

		///<summary>
		/// aboutpage brand images
		///</summary>
		[ImplementPropertyType("aboutpageBrandImages")]
		public IEnumerable<IPublishedContent> AboutpageBrandImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("aboutpageBrandImages"); }
		}

		///<summary>
		/// aboutpage brand title
		///</summary>
		[ImplementPropertyType("aboutpageBrandTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> AboutpageBrandTitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("aboutpageBrandTitle"); }
		}

		///<summary>
		/// aboutpage description
		///</summary>
		[ImplementPropertyType("aboutpageDescription")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> AboutpageDescription
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("aboutpageDescription"); }
		}

		///<summary>
		/// aboutpage hero image
		///</summary>
		[ImplementPropertyType("aboutpageHeroImage")]
		public IPublishedContent AboutpageHeroImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("aboutpageHeroImage"); }
		}

		///<summary>
		/// aboutpage service description
		///</summary>
		[ImplementPropertyType("aboutpageServiceDescription")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> AboutpageServiceDescription
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("aboutpageServiceDescription"); }
		}

		///<summary>
		/// aboutpage service list
		///</summary>
		[ImplementPropertyType("aboutpageServiceList")]
		public Our.Umbraco.Vorto.Models.VortoValue<IEnumerable<string>> AboutpageServiceList
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IEnumerable<string>>>("aboutpageServiceList"); }
		}

		///<summary>
		/// aboutpage service title
		///</summary>
		[ImplementPropertyType("aboutpageServiceTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> AboutpageServiceTitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("aboutpageServiceTitle"); }
		}

		///<summary>
		/// aboutpage title
		///</summary>
		[ImplementPropertyType("aboutpageTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> AboutpageTitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("aboutpageTitle"); }
		}
	}

	/// <summary>Login Page Declaration</summary>
	[PublishedContentModel("loginPageDeclaration")]
	public partial class LoginPageDeclaration : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "loginPageDeclaration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LoginPageDeclaration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LoginPageDeclaration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// form image
		///</summary>
		[ImplementPropertyType("formImage")]
		public IPublishedContent FormImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("formImage"); }
		}
	}

	/// <summary>Home Page Banner</summary>
	[PublishedContentModel("homePageBanner")]
	public partial class HomePageBanner : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageBanner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageBanner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageBanner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// banner image
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("bannerImage"); }
		}

		///<summary>
		/// banner subtitle
		///</summary>
		[ImplementPropertyType("bannerSubtitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> BannerSubtitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("bannerSubtitle"); }
		}

		///<summary>
		/// banner summary
		///</summary>
		[ImplementPropertyType("bannerSummary")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> BannerSummary
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("bannerSummary"); }
		}

		///<summary>
		/// banner title
		///</summary>
		[ImplementPropertyType("bannerTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> BannerTitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("bannerTitle"); }
		}
	}

	/// <summary>Home Page Product</summary>
	[PublishedContentModel("homePageProduct")]
	public partial class HomePageProduct : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageProduct";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageProduct(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageProduct, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// product image
		///</summary>
		[ImplementPropertyType("productImage")]
		public IPublishedContent ProductImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("productImage"); }
		}

		///<summary>
		/// product name
		///</summary>
		[ImplementPropertyType("productName")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> ProductName
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("productName"); }
		}
	}

	/// <summary>Home Page Feature</summary>
	[PublishedContentModel("homePageFeature")]
	public partial class HomePageFeature : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageFeature";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageFeature(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageFeature, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// feature description
		///</summary>
		[ImplementPropertyType("featureDescription")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> FeatureDescription
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("featureDescription"); }
		}

		///<summary>
		/// feature image
		///</summary>
		[ImplementPropertyType("featureImage")]
		public IPublishedContent FeatureImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("featureImage"); }
		}

		///<summary>
		/// feature name
		///</summary>
		[ImplementPropertyType("featureName")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> FeatureName
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("featureName"); }
		}

		///<summary>
		/// feature price
		///</summary>
		[ImplementPropertyType("featurePrice")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> FeaturePrice
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("featurePrice"); }
		}

		///<summary>
		/// feature review
		///</summary>
		[ImplementPropertyType("featureReview")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> FeatureReview
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("featureReview"); }
		}
	}

	/// <summary>Home Page Section 4</summary>
	[PublishedContentModel("homePageSection4")]
	public partial class HomePageSection4 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageSection4";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageSection4(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageSection4, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// home section 4 description
		///</summary>
		[ImplementPropertyType("homeSection4Description")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection4Description
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection4Description"); }
		}

		///<summary>
		/// home section 4 header
		///</summary>
		[ImplementPropertyType("homeSection4Header")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection4Header
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection4Header"); }
		}

		///<summary>
		/// home section 4 title
		///</summary>
		[ImplementPropertyType("homeSection4Title")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection4Title
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection4Title"); }
		}

		///<summary>
		/// home section 4 title expand
		///</summary>
		[ImplementPropertyType("homeSection4TitleExpand")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> HomeSection4TitleExpand
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("homeSection4TitleExpand"); }
		}
	}

	/// <summary>Home Page Plan</summary>
	[PublishedContentModel("homePagePlan")]
	public partial class HomePagePlan : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePagePlan";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePagePlan(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePagePlan, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// plan advance 1 content
		///</summary>
		[ImplementPropertyType("planAdvance1Content")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanAdvance1Content
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planAdvance1Content"); }
		}

		///<summary>
		/// plan advance 1 title
		///</summary>
		[ImplementPropertyType("planAdvance1Title")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanAdvance1Title
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planAdvance1Title"); }
		}

		///<summary>
		/// plan advance 2 content
		///</summary>
		[ImplementPropertyType("planAdvance2Content")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanAdvance2Content
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planAdvance2Content"); }
		}

		///<summary>
		/// plan advance 2 title
		///</summary>
		[ImplementPropertyType("planAdvance2Title")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanAdvance2Title
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planAdvance2Title"); }
		}

		///<summary>
		/// plan advance 3 content
		///</summary>
		[ImplementPropertyType("planAdvance3Content")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanAdvance3Content
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planAdvance3Content"); }
		}

		///<summary>
		/// plan advance 3 title
		///</summary>
		[ImplementPropertyType("planAdvance3Title")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanAdvance3Title
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planAdvance3Title"); }
		}

		///<summary>
		/// plan benefit list
		///</summary>
		[ImplementPropertyType("planBenefitList")]
		public Our.Umbraco.Vorto.Models.VortoValue<IEnumerable<string>> PlanBenefitList
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IEnumerable<string>>>("planBenefitList"); }
		}

		///<summary>
		/// plan image
		///</summary>
		[ImplementPropertyType("planImage")]
		public IPublishedContent PlanImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("planImage"); }
		}

		///<summary>
		/// plan name
		///</summary>
		[ImplementPropertyType("planName")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanName
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planName"); }
		}

		///<summary>
		/// plan summary
		///</summary>
		[ImplementPropertyType("planSummary")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanSummary
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planSummary"); }
		}

		///<summary>
		/// plan title
		///</summary>
		[ImplementPropertyType("planTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlanTitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planTitle"); }
		}
	}

	/// <summary>Home Page Body</summary>
	[PublishedContentModel("homePageBody")]
	public partial class HomePageBody : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageBody";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageBody(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageBody, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// placeholder Temp
		///</summary>
		[ImplementPropertyType("placeholderTemp")]
		public string PlaceholderTemp
		{
			get { return this.GetPropertyValue<string>("placeholderTemp"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
